##### Terminal #####
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm*:RGB'

##### Prefix (Leader) #####
set -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

##### Pane Splits #####
unbind %
bind-key h split-window -h
unbind '"'
bind-key v split-window -v

##### Pane & Window Management #####
bind-key x kill-pane
bind-key -r m resize-pane -Z
bind-key . command-prompt "rename-session '%%'"

##### Reload Config #####
unbind r
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded!"

##### Mouse & UI #####
set -g mouse on
set -g status-position top
set -g status-bg colour244

# Configure status bar sides
set -g status-left ""
set -g status-right-length 50
set -g status-right " #S "

##### Indexing & Naming #####
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
